- id: modernize
  name: modernize
  entry: modernize
  files: '\.go$'
  language: "script"
  description: Runs `modernize`

- id: gofumpt
  name: gofumpt
  entry: gofumpt
  files: '\.go$'
  language: "script"
  description: Runs `gofumpt`

- id: goimports-rereviser
  name: goimports-rereviser
  entry: goimports-rereviser
  files: '\.go$'
  language: script
  description: Runs `goimports-rereviser`

- id: golangci-lint
  name: golangci-lint
  entry: golangci-lint
  files: '\.go$'
  language: script
  description: Runs `golangci-lint`
