name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  prek:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - name: Install prek
        uses: j178/prek-action@v2
        with:
          install-only: true
      - name: Validate .pre-commit-hooks.yaml
        run: |
          prek --verbose --color=always validate-manifest .pre-commit-hooks.yaml

  shellcheck:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - name: Install ShellCheck
        run: |
          curl -sSL https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz | sudo tar -xJf - -C /usr/local/bin --strip-components=1 shellcheck-latest/shellcheck
      - name: Run ShellCheck
        run: |
          /usr/local/bin/shellcheck ./*.bash
